<a href="https://colab.research.google.com/github/A5112-ctrl/Books-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy as Multi dimensional array

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
List=([1,2,3],[4,5,6],[7,3,2])
matrix=np.array(List)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 3, 2]])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [8]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.zeros((2,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [42]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:

np.random.rand(3,2)

array([[0.30169775, 0.07451321],
       [0.50184521, 0.79716504],
       [0.11897179, 0.1494074 ]])

In [19]:
np.random.randn(3,2)

array([[-0.06229808, -0.86611532],
       [-2.36366632, -1.00816585],
       [-0.21610162,  1.05748929]])

In [20]:
np.random.randint(2,8)

4

In [21]:
array=np.arange(10)

In [22]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
rand_array=np.random.rand(10)
rand_array

array([0.62326656, 0.2385315 , 0.91790282, 0.01881907, 0.55443186,
       0.54901498, 0.8241269 , 0.67091266, 0.93445226, 0.26993793])

In [26]:
rand_array.reshape(2,5)

array([[0.62326656, 0.2385315 , 0.91790282, 0.01881907, 0.55443186],
       [0.54901498, 0.8241269 , 0.67091266, 0.93445226, 0.26993793]])

In [27]:
rand_array.argmin()

3

In [29]:
rand_array.max()

0.9344522580868534

In [30]:
rand_array.min()

0.01881906804514244

In [35]:
a=np.random.rand(3,2)
a

array([[0.59132144, 0.54935384],
       [0.7068581 , 0.40481208],
       [0.25791863, 0.58437101]])

In [36]:
a.T

array([[0.59132144, 0.7068581 , 0.25791863],
       [0.54935384, 0.40481208, 0.58437101]])

In [40]:
b=np.eye(5)
b


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
b.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.arange(4,50)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
sample=np.arange(5,20)
sample

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
sample[3]

8

In [53]:
sample[3:7]

array([ 8,  9, 10, 11])

In [54]:
sample[2:6]=67

In [59]:
sample

array([54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54])

In [62]:
sample[:3]=12
sample

array([12, 12, 12, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54])

In [64]:
subset=sample[0:6]
subset

array([12, 12, 12, 54, 54, 54])

2D Array


In [65]:
import numpy as np

In [68]:
matrix=np.array([[2,3,4],[6,8,1],[7,9,3]])
matrix

array([[2, 3, 4],
       [6, 8, 1],
       [7, 9, 3]])

In [70]:
matrix[0:2]

array([[2, 3, 4],
       [6, 8, 1]])

In [72]:
matrix[2:,1]

array([9])

In [74]:
matrix[:,1]

array([3, 8, 9])

In [76]:
matrix[2
      ]

array([7, 9, 3])

In [77]:
matrix[:,(2,0)]

array([[4, 2],
       [1, 6],
       [3, 7]])

In [78]:
matrix+matrix

array([[ 4,  6,  8],
       [12, 16,  2],
       [14, 18,  6]])

In [81]:
matrix+2*matrix

array([[ 6,  9, 12],
       [18, 24,  3],
       [21, 27,  9]])

In [82]:
np.exp(matrix)

array([[7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [4.03428793e+02, 2.98095799e+03, 2.71828183e+00],
       [1.09663316e+03, 8.10308393e+03, 2.00855369e+01]])

In [84]:
np.sqrt(matrix)

array([[1.41421356, 1.73205081, 2.        ],
       [2.44948974, 2.82842712, 1.        ],
       [2.64575131, 3.        , 1.73205081]])

In [85]:
np.square(matrix)

array([[ 4,  9, 16],
       [36, 64,  1],
       [49, 81,  9]])

In [86]:
np.log(matrix)

array([[0.69314718, 1.09861229, 1.38629436],
       [1.79175947, 2.07944154, 0.        ],
       [1.94591015, 2.19722458, 1.09861229]])

In [87]:
np.argmax(matrix)

7

In [88]:
matrix

array([[2, 3, 4],
       [6, 8, 1],
       [7, 9, 3]])

In [90]:
np.argmin(matrix)

5

In [93]:
np.max(matrix)

9

In [97]:
np.min(matrix),np.argmin(matrix)

(1, 5)

In [98]:
np.mean(matrix)

4.777777777777778

In [99]:
np.var(matrix)

7.06172839506173

In [100]:
np.std(matrix)

2.657391276244755

In [102]:
array=np.random.rand(2,4)
array

array([[0.15690725, 0.00468319, 0.675934  , 0.84263692],
       [0.27115088, 0.99163506, 0.95001388, 0.76493841]])

In [103]:
array.T

array([[0.15690725, 0.27115088],
       [0.00468319, 0.99163506],
       [0.675934  , 0.95001388],
       [0.84263692, 0.76493841]])

In [104]:
np.round(array,decimals=2)

array([[0.16, 0.  , 0.68, 0.84],
       [0.27, 0.99, 0.95, 0.76]])

In [105]:
sports=(["cricket","golf","football","cricket"])
sports

['cricket', 'golf', 'football', 'cricket']

In [106]:
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')